<?php

namespace app\modules\photo\modules\admin\models;
use app\modules\photo\modules\admin\models\ImageUpload;

use Yii;

/**
 * This is the model class for table "image".
 *
 * @property int $id
 * @property string|null $author
 * @property string|null $category
 * @property string|null $title
 * @property string|null $date
 * @property string|null $status
 * @property string|null $extension
 * @property string|null $slug
 * @property string|null $image
 */
class ImageModel extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'image';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date'], 'safe'],
            [['author', 'category', 'title', 'status', 'extension', 'image', 'key'], 'string', 'max' => 255],
            [['date'], 'default', 'value' => date('Y-m-d H:i:s')],
            [['key'], 'default', 'value' => '0']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'author' => 'Author',
            'category' => 'Category',
            'title' => 'Title',
            'date' => 'Date',
            'status' => 'Status',
            'extension' => 'Extension',
            'image' => 'Image',
        ];
    }

    public function saveImage($id, $ext)
    {
         $this->image = ($id . "." .  $ext);
         return $this->save();
    }


    public function deleteImage()
    {
         $imageUploadModel = new ImageUpload();
         if( file_exists(Yii::getAlias('../web/images/photogallery/')  . ($this->id . "." .  $this->extension) ))
         {
          unlink(Yii::getAlias('../web/images/photogallery/')  . ($this->id . "." .  $this->extension));
         }

    }

    public function beforeDelete()
     {
         $this->deleteImage();
         return parent::beforeDelete(); // TODO: Change the autogenerated stub
     }


     public function getWaterList()
     {
          return [
               '0' => 'do not use',
               '1' => 'left top',
               '2' => 'right top',
               '3' => 'left bottom',
               '4' => 'right bottom',
          ];
     }

     public function change_images_keys()
     {
          return $this->save();
     }

}
